receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

processors:
  filter/service-a-metrics:
    error_mode: ignore
    metrics:
      include:
        match_type: strict
        resource_attributes:
          - key: service.name
            value: "service-a"
  filter/not-service-a-metrics:
    error_mode: ignore
    metrics:
      exclude:
        match_type: strict
        resource_attributes:
          - key: service.name
            value: "service-a"
  filter/service-a-logs:
    error_mode: ignore
    logs:
      include:
        match_type: strict
        resource_attributes:
          - key: service.name
            value: "service-a"
  filter/not-service-a-logs:
    error_mode: ignore
    metrics:
      exclude:
        match_type: strict
        resource_attributes:
          - key: service.name
            value: "service-a"
  batch:

exporters:
  awsemf:
    region: ${env:AWS_REGION}
    log_group_name: ${env:CW_METRICS_EMF_LOG_GROUP_NAME}
    log_stream_name: ${env:CW_METRICS_EMF_LOG_STREAM_NAME}
    namespace: ${env:CW_METRICS_NAMESPACE}
    dimension_rollup_option: "NoDimensionRollup"
    log_retention: 7
  awscloudwatchlogs:
    log_group_name: ${env:CW_LOG_GROUP_NAME}
    log_stream_name: ${env:CW_LOG_STREAM_NAME}
    raw_log: true
    region: ${env:AWS_REGION}
    log_retention: 7
  awsxray:
    region: ${env:AWS_REGION}
  otlphttp/counter:
    endpoint: ${env:OTEL_LOCAL_COUNTER}
    compression: none
    encoding: json
    tls:
      insecure: true

service:
  pipelines:
    logs/service-a:
      receivers: [otlp]
      processors: [filter/service-a-logs, batch]
      exporters: [awscloudwatchlogs]
    logs/others:
      receivers: [otlp]
      processors: [filter/not-service-a-logs, batch]
      exporters: [otlphttp/counter]
    metrics/service-a:
      receivers: [otlp]
      processors: [filter/service-a-metrics, batch]
      exporters: [awsemf]
    metrics/others:
      receivers: [otlp]
      processors: [filter/not-service-a-metrics, batch]
      exporters: [otlphttp/counter]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [awsxray]